
package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Get UK Postcode,Town,County and Validate UK Address
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UKLocation", targetNamespace = "http://www.webserviceX.NET", wsdlLocation = "http://www.webservicex.net/uklocation.asmx?WSDL")
public class UKLocation
    extends Service
{

    private final static URL UKLOCATION_WSDL_LOCATION;
    private final static WebServiceException UKLOCATION_EXCEPTION;
    private final static QName UKLOCATION_QNAME = new QName("http://www.webserviceX.NET", "UKLocation");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.webservicex.net/uklocation.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UKLOCATION_WSDL_LOCATION = url;
        UKLOCATION_EXCEPTION = e;
    }

    public UKLocation() {
        super(__getWsdlLocation(), UKLOCATION_QNAME);
    }

    public UKLocation(WebServiceFeature... features) {
        super(__getWsdlLocation(), UKLOCATION_QNAME, features);
    }

    public UKLocation(URL wsdlLocation) {
        super(wsdlLocation, UKLOCATION_QNAME);
    }

    public UKLocation(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UKLOCATION_QNAME, features);
    }

    public UKLocation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UKLocation(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UKLocationSoap
     */
    @WebEndpoint(name = "UKLocationSoap")
    public UKLocationSoap getUKLocationSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET", "UKLocationSoap"), UKLocationSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UKLocationSoap
     */
    @WebEndpoint(name = "UKLocationSoap")
    public UKLocationSoap getUKLocationSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET", "UKLocationSoap"), UKLocationSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UKLOCATION_EXCEPTION!= null) {
            throw UKLOCATION_EXCEPTION;
        }
        return UKLOCATION_WSDL_LOCATION;
    }

}
